version: 2
jobs:
  build-node13:
    docker:
      - image: circleci/node:13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  build-node12:
    docker:
      - image: circleci/node:12-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  build-node10:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci

  deploy:
    docker:
      - image: circleci/node:10-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run ci
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # To help debug when lerna detects changes to the working tree
      - run: git status
      # the yarn.lock and some other generated files may change due to running
      # the build with the newly commited version numbers
      # resetting the working tree avoids lerna errors due to unclean working trees
      - run: git reset --hard
      - run: yarn run lerna:publish

workflows:
  version: 2
  build:
    jobs:
      - build-node13
      - build-node12
      - build-node10
      - deploy:
          filters:
            tags:
              only: /^RELEASE/
            branches:
              ignore: /.*/
